use std::path::PathBuf;
use tracing::info;

pub struct MqttClientConfig {
    pub client_id: String,
    pub host: String,
    pub port: u16,
}

impl MqttClientConfig {
    fn from_env() -> Self {
        let client_id = std::env::var("MQTT_CLIENT_ID")
            .unwrap_or_else(|_| "placenet-home".to_string());
        let host = "localhost".to_string();
        let port: u16 = std::env::var("MQTT_PORT")
            .unwrap_or_else(|_| "1883".to_string())
            .parse()
            .unwrap_or(1883);

        Self { client_id, host, port}
    }
}

pub struct MqttBrokerageConfig {
    pub port: u16,
    pub client_id: String,
    pub config_file: PathBuf,
    pub password_file: PathBuf,
}

impl MqttBrokerageConfig {
    fn from_env(config_dir: &PathBuf) -> Self {
        let port: u16 = std::env::var("MQTT_PORT")
            .unwrap_or_else(|_| "1883".to_string())
            .parse()
            .unwrap_or(1883);
        let client_id = std::env::var("MQTT_CLIENT_ID")
            .unwrap_or_else(|_| "placenet-home".to_string());
        let config_file = config_dir.join("mosquitto.conf");
        let password_file = config_dir.join("passwd");
        Self { port, client_id, config_file, password_file }
    }

    /// Generate the mosquitto.conf file at `self.config_file`
    pub async fn write_config(&self, require_auth: bool) -> Result<(), String> {
        let config_dir = self.config_file.parent()
            .ok_or_else(|| "config_file has no parent directory".to_string())?;

        tokio::fs::create_dir_all(config_dir)
            .await
            .map_err(|e| format!("Failed to create config dir: {}", e))?;

        let mut config = format!(
            "# Auto-generated by placenet-home\n\
             listener {}\n\
             persistence false\n\
             log_dest stderr\n",
            self.port
        );

        if require_auth {
            config.push_str(&format!(
                "allow_anonymous false\n\
                 password_file {}\n",
                self.password_file.display()
            ));
        } else {
            config.push_str("allow_anonymous true\n");
        }

        tokio::fs::write(&self.config_file, &config)
            .await
            .map_err(|e| format!("Failed to write mosquitto.conf: {}", e))?;

        info!("Wrote mosquitto config to {}", self.config_file.display());
        Ok(())
    }
}

pub struct Config {
    pub mqtt_brokerage: MqttBrokerageConfig,
    pub mqtt_client: MqttClientConfig,
    pub config_dir: PathBuf,
}

impl Config {
    /// Load configuration from environment variables, falling back to defaults.
    pub fn from_env() -> Self {
        let config_dir = PathBuf::from(
            std::env::var("PLACENET_CONFIG_DIR").unwrap_or_else(|_| "config".to_string()),
        );
        let mqtt_brokerage = MqttBrokerageConfig::from_env(&config_dir);
        let mqtt_client = MqttClientConfig::from_env();
        Self { mqtt_brokerage, mqtt_client, config_dir }
    }
}
