use std::path::PathBuf;
use tracing::info;

pub struct MqttClientConfig {
    pub client_id: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub password: String,
    pub tls_enabled: bool,
    /// Path to the CA certificate used to verify the broker's TLS certificate.
    pub cafile: PathBuf,
}

impl MqttClientConfig {
    fn from_env(config_dir: &PathBuf) -> Self {
        let client_id = std::env::var("MQTT_CLIENT_ID")
            .unwrap_or_else(|_| "placenet-home".to_string());
        let host = "localhost".to_string();
        let tls_enabled = std::env::var("MQTT_TLS_ENABLED")
            .unwrap_or_else(|_| "false".to_string())
            .trim()
            .eq_ignore_ascii_case("true");
        let port: u16 = if tls_enabled {
            std::env::var("MQTTS_PORT")
                .unwrap_or_else(|_| "8883".to_string())
                .parse()
                .unwrap_or(8883)
        } else {
            std::env::var("MQTT_PORT")
                .unwrap_or_else(|_| "1883".to_string())
                .parse()
                .unwrap_or(1883)
        };
        let username = std::env::var("MQTT_USERNAME")
            .unwrap_or_else(|_| "placenet".to_string());
        let password = std::env::var("MQTT_PASSWORD")
            .unwrap_or_else(|_| "changeme".to_string());
        let cafile = config_dir.join(
            std::env::var("MQTT_CAFILE").unwrap_or_else(|_| "certs/ca.crt".to_string()),
        );

        Self { client_id, host, port, username, password, tls_enabled, cafile }
    }
}

pub struct MqttBrokerageConfig {
    pub port: u16,
    pub client_id: String,
    pub config_file: PathBuf,
    pub password_file: PathBuf,
    pub username: String,
    pub password: String,
    pub tls_enabled: bool,
    pub mqtts_port: u16,
    /// Path to the CA certificate (used by Mosquitto for client verification if needed).
    pub cafile: PathBuf,
    /// Path to the broker's TLS certificate.
    pub certfile: PathBuf,
    /// Path to the broker's TLS private key.
    pub keyfile: PathBuf,
}

impl MqttBrokerageConfig {
    fn from_env(config_dir: &PathBuf) -> Self {
        let port: u16 = std::env::var("MQTT_PORT")
            .unwrap_or_else(|_| "1883".to_string())
            .parse()
            .unwrap_or(1883);
        let mqtts_port: u16 = std::env::var("MQTTS_PORT")
            .unwrap_or_else(|_| "8883".to_string())
            .parse()
            .unwrap_or(8883);
        let client_id = std::env::var("MQTT_CLIENT_ID")
            .unwrap_or_else(|_| "placenet-home".to_string());
        let username = std::env::var("MQTT_USERNAME")
            .unwrap_or_else(|_| "placenet".to_string());
        let password = std::env::var("MQTT_PASSWORD")
            .unwrap_or_else(|_| "changeme".to_string());
        let tls_enabled = std::env::var("MQTT_TLS_ENABLED")
            .unwrap_or_else(|_| "false".to_string())
            .trim()
            .eq_ignore_ascii_case("true");
        let cafile = config_dir.join(
            std::env::var("MQTT_CAFILE").unwrap_or_else(|_| "certs/ca.crt".to_string()),
        );
        let certfile = config_dir.join(
            std::env::var("MQTT_CERTFILE").unwrap_or_else(|_| "certs/broker.crt".to_string()),
        );
        let keyfile = config_dir.join(
            std::env::var("MQTT_KEYFILE").unwrap_or_else(|_| "certs/broker.key".to_string()),
        );
        let config_file = config_dir.join("mosquitto.conf");
        let password_file = config_dir.join("passwd");
        Self {
            port,
            mqtts_port,
            client_id,
            config_file,
            password_file,
            username,
            password,
            tls_enabled,
            cafile,
            certfile,
            keyfile,
        }
    }

    /// Generate the mosquitto.conf file at `self.config_file`.
    ///
    /// Authentication is always required. When `tls_enabled` is true a TLS
    /// listener is emitted on `mqtts_port` and the plain listener is omitted
    /// to force all traffic through the encrypted channel.
    pub async fn write_config(&self) -> Result<(), String> {
        let config_dir = self.config_file.parent()
            .ok_or_else(|| "config_file has no parent directory".to_string())?;

        tokio::fs::create_dir_all(config_dir)
            .await
            .map_err(|e| format!("Failed to create config dir: {}", e))?;

        let mut config = String::from("# Auto-generated by placenet-home\n");
        config.push_str("persistence false\n");
        config.push_str("log_dest stderr\n\n");

        if self.tls_enabled {
            // Plain listener is omitted when TLS is enabled to force all
            // traffic through the encrypted channel.
            config.push_str(&format!(
                "listener {}\n\
                 protocol mqtt\n\
                 cafile {}\n\
                 certfile {}\n\
                 keyfile {}\n\
                 tls_version tlsv1.2\n\
                 require_certificate false\n\
                 allow_anonymous false\n\
                 password_file {}\n",
                self.mqtts_port,
                self.cafile.display(),
                self.certfile.display(),
                self.keyfile.display(),
                self.password_file.display(),
            ));
        } else {
            config.push_str(&format!(
                "listener {}\n\
                 allow_anonymous false\n\
                 password_file {}\n",
                self.port,
                self.password_file.display(),
            ));
        }

        tokio::fs::write(&self.config_file, &config)
            .await
            .map_err(|e| format!("Failed to write mosquitto.conf: {}", e))?;

        info!("Wrote mosquitto config to {}", self.config_file.display());
        Ok(())
    }
}

pub struct HttpConfig {
    pub host: String,
    pub port: u16,
    pub tls_enabled: bool,
}

impl HttpConfig {
    fn from_env() -> Self {
        let host = std::env::var("HTTP_HOST").unwrap_or_else(|_| "0.0.0.0".to_string());
        let port: u16 = std::env::var("HTTP_PORT")
            .unwrap_or_else(|_| "8080".to_string())
            .parse()
            .unwrap_or(8080);
        let tls_enabled = std::env::var("HTTP_TLS_ENABLED")
            .unwrap_or_else(|_| "true".to_string())
            .trim()
            .eq_ignore_ascii_case("true");
        Self { host, port, tls_enabled }
    }
}

/// Configuration for connecting to a peer placenet-home server.
pub struct PeerConfig {
    /// Base URL of the peer server, e.g. "http://192.168.1.42:8080"
    pub peer_url: Option<String>,
}

impl PeerConfig {
    fn from_env() -> Self {
        let peer_url = std::env::var("PEER_URL").ok();
        Self { peer_url }
    }
}

pub struct Config {
    pub mqtt_brokerage: MqttBrokerageConfig,
    pub mqtt_client: MqttClientConfig,
    pub http: HttpConfig,
    pub peer: PeerConfig,
    pub config_dir: PathBuf,
}

impl Config {
    /// Load configuration from environment variables, falling back to defaults.
    pub fn from_env() -> Self {
        let config_dir = PathBuf::from(
            std::env::var("PLACENET_CONFIG_DIR").unwrap_or_else(|_| "config".to_string()),
        );
        let mqtt_brokerage = MqttBrokerageConfig::from_env(&config_dir);
        let mqtt_client = MqttClientConfig::from_env(&config_dir);
        let http = HttpConfig::from_env();
        let peer = PeerConfig::from_env();
        Self { mqtt_brokerage, mqtt_client, http, peer, config_dir }
    }
}
