use std::path::PathBuf;
use async_trait::async_trait;
use tokio::process::{Child, Command};
use tokio::io::AsyncBufReadExt;
use tracing::{info, error};

use crate::supervisor::ManagedService;

/// Manages a Mosquitto MQTT broker child process
pub struct MosquittoService {
    binary_path: String,
    passwd_binary: Option<String>,
    config_dir: PathBuf,
    child: Option<Child>,
}

impl MosquittoService {
    pub fn new(binary_path: String, passwd_binary: Option<String>, config_dir: PathBuf) -> Self {
        Self {
            binary_path,
            passwd_binary,
            config_dir,
            child: None,
        }
    }

    /// Generate the mosquitto.conf file in the config directory
    pub async fn write_config(
        &self,
        port: u16,
        require_auth: bool,
    ) -> Result<PathBuf, String> {
        tokio::fs::create_dir_all(&self.config_dir)
            .await
            .map_err(|e| format!("Failed to create config dir: {}", e))?;

        let config_path = self.config_dir.join("mosquitto.conf");
        let password_file = self.config_dir.join("passwd");

        let mut config = format!(
            "# Auto-generated by placenet-home\n\
             listener {port}\n\
             persistence false\n\
             log_dest stderr\n"
        );

        if require_auth {
            config.push_str(&format!(
                "allow_anonymous false\n\
                 password_file {}\n",
                password_file.display()
            ));
        } else {
            config.push_str("allow_anonymous true\n");
        }

        tokio::fs::write(&config_path, &config)
            .await
            .map_err(|e| format!("Failed to write mosquitto.conf: {}", e))?;

        info!("Wrote mosquitto config to {}", config_path.display());
        Ok(config_path)
    }

    /// Add or update a user's password using mosquitto_passwd
    pub async fn set_password(&self, username: &str, password: &str) -> Result<(), String> {
        let passwd_bin = self.passwd_binary.as_deref()
            .ok_or_else(|| "mosquitto_passwd is not installed".to_string())?;

        let password_file = self.config_dir.join("passwd");

        // Create the file if it doesn't exist
        if !password_file.exists() {
            // -c creates a new file, -b reads password from command line
            let output = Command::new(passwd_bin)
                .args(["-c", "-b"])
                .arg(&password_file)
                .arg(username)
                .arg(password)
                .output()
                .await
                .map_err(|e| format!("Failed to run mosquitto_passwd: {}", e))?;

            if !output.status.success() {
                return Err(format!(
                    "mosquitto_passwd failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
        } else {
            // -b reads password from command line (no -c, appends/updates)
            let output = Command::new(passwd_bin)
                .arg("-b")
                .arg(&password_file)
                .arg(username)
                .arg(password)
                .output()
                .await
                .map_err(|e| format!("Failed to run mosquitto_passwd: {}", e))?;

            if !output.status.success() {
                return Err(format!(
                    "mosquitto_passwd failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
        }

        info!("Set password for MQTT user: {}", username);
        Ok(())
    }

    /// Delete a user from the password file
    pub async fn delete_user(&self, username: &str) -> Result<(), String> {
        let passwd_bin = self.passwd_binary.as_deref()
            .ok_or_else(|| "mosquitto_passwd is not installed".to_string())?;

        let password_file = self.config_dir.join("passwd");

        if !password_file.exists() {
            return Err("Password file does not exist".to_string());
        }

        let output = Command::new(passwd_bin)
            .arg("-D")
            .arg(&password_file)
            .arg(username)
            .output()
            .await
            .map_err(|e| format!("Failed to run mosquitto_passwd: {}", e))?;

        if !output.status.success() {
            return Err(format!(
                "mosquitto_passwd failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }

        info!("Deleted MQTT user: {}", username);
        Ok(())
    }

    fn config_path(&self) -> PathBuf {
        self.config_dir.join("mosquitto.conf")
    }
}

#[async_trait]
impl ManagedService for MosquittoService {
    async fn start(&mut self) -> Result<u32, String> {
        if self.child.is_some() {
            return Err("Mosquitto is already running".to_string());
        }

        let config = self.config_path();
        if !config.exists() {
            return Err(format!(
                "Config file not found at {}. Call write_config() first.",
                config.display()
            ));
        }

        let mut child = Command::new(&self.binary_path)
            .args(["-c", &config.to_string_lossy()])
            .stderr(std::process::Stdio::piped())
            .stdout(std::process::Stdio::null())
            .spawn()
            .map_err(|e| format!("Failed to spawn mosquitto: {}", e))?;

        let pid = child.id().ok_or("Failed to get mosquitto PID")?;

        // Spawn a task to capture and log stderr
        if let Some(stderr) = child.stderr.take() {
            let reader = tokio::io::BufReader::new(stderr);
            tokio::spawn(async move {
                let mut lines = reader.lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    info!(target: "mosquitto", "{}", line);
                }
            });
        }

        self.child = Some(child);
        Ok(pid)
    }

    async fn stop(&mut self) -> Result<(), String> {
        if let Some(mut child) = self.child.take() {
            // Send SIGTERM first for graceful shutdown
            let pid = child.id();
            if let Some(pid) = pid {
                unsafe {
                    libc::kill(pid as i32, libc::SIGTERM);
                }
            }

            // Wait briefly for graceful shutdown, then force kill
            match tokio::time::timeout(
                std::time::Duration::from_secs(5),
                child.wait(),
            ).await {
                Ok(Ok(status)) => {
                    info!("Mosquitto exited with status: {}", status);
                }
                Ok(Err(e)) => {
                    error!("Error waiting for mosquitto: {}", e);
                }
                Err(_) => {
                    info!("Mosquitto didn't exit gracefully, killing");
                    let _ = child.kill().await;
                }
            }

            Ok(())
        } else {
            Err("Mosquitto is not running".to_string())
        }
    }

    async fn is_running(&mut self) -> bool {
        if let Some(child) = &mut self.child {
            // try_wait returns Ok(Some(status)) if exited, Ok(None) if still running
            match child.try_wait() {
                Ok(Some(_)) => {
                    self.child = None;
                    false
                }
                Ok(None) => true,
                Err(_) => false,
            }
        } else {
            false
        }
    }
}
